name: 'CI'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - run: cargo test
