name: 'CI'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
    paths:
      - '**.rs'

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint_and_test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}
      - run: |
          cargo clippy --all-targets --all-features
          cargo fmt -- --check
      - run: |
          cargo test
