name: 'Crates'

on:
  push:
    tags:
      - 'v*'           # Push events to every tag not containing /
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: rust-release-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            rust-release-${{ runner.os }}
            rust-
      - name: Publish on crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
