name: 'Release'

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    paths:
      - '.github/workflows/release.yml'
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/release.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    timeout-minutes: 30
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      - uses: jiacai2050/zigcc@main
        with:
          zig-version: master
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}
      - run: |
          rustup target add ${{ matrix.target }}
          zigcargo build --release --target ${{ matrix.target }}
        env:
          ZIGCC_LOG: 1
          ZIGCC_BLACKLIST_FLAGS: "self-contained/rcrt1.o self-contained/crti.o"
