name: 'Release'

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    timeout-minutes: 30
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      - uses: jiacai2050/zigcc@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}
      - run: |
          rustup target add ${{ matrix.target }}
          zigcargo build --release --target ${{ matrix.target }}
